### ISSUE TITLE
Visual Editor not working

### ISSUE THREAD

**Issue by stephend2000** [ElNovi/mediawiki-skins-Timeless#2]
The edit button appears for a second and then disappears. I am using MediaWiki 1.27.0 and desperately need this theme for my new site ASAP! Thank you for your hard work

**Comment by stephend2000** [comment]
Forgot to add the SupportedSkins tag, yet the User Page and User Talk pages are giving errors

`MediaWiki internal error.

Original exception: [9e4e0e4e321e9a53c01592ef] /index.php?title=User:Stephen MWException from line 553 of /var/www/vhosts/coldplay.wiki/httpdocs/includes/Html.php: HTML attribute tooltip-params can not contain a list of values
Backtrace:
#0 /var/www/vhosts/coldplay.wiki/httpdocs/includes/Html.php(296): Html::expandAttributes(array)
#1 /var/www/vhosts/coldplay.wiki/httpdocs/includes/Html.php(211): Html::openElement(string, array)
#2 /var/www/vhosts/coldplay.wiki/httpdocs/skins/Timeless/TimelessTemplate.php(281): Html::rawElement(string, array, string)
#3 /var/www/vhosts/coldplay.wiki/httpdocs/includes/skins/BaseTemplate.php(453): TimelessTemplate->makeLink(string, array, array)
#4 /var/www/vhosts/coldplay.wiki/httpdocs/skins/Timeless/TimelessTemplate.php(226): BaseTemplate->makeListItem(string, array)
#5 /var/www/vhosts/coldplay.wiki/httpdocs/skins/Timeless/TimelessTemplate.php(122): TimelessTemplate->assemblePortlet(array)
#6 /var/www/vhosts/coldplay.wiki/httpdocs/includes/skins/SkinTemplate.php(248): TimelessTemplate->execute()
#7 /var/www/vhosts/coldplay.wiki/httpdocs/includes/OutputPage.php(2324): SkinTemplate->outputPage()
#8 /var/www/vhosts/coldplay.wiki/httpdocs/includes/MediaWiki.php(753): OutputPage->output()
#9 /var/www/vhosts/coldplay.wiki/httpdocs/includes/MediaWiki.php(519): MediaWiki->main()
#10 /var/www/vhosts/coldplay.wiki/httpdocs/index.php(43): MediaWiki->run()
#11 {main}

Exception caught inside exception handler: [9e4e0e4e321e9a53c01592ef] /index.php?title=User:Stephen MWException from line 553 of /var/www/vhosts/coldplay.wiki/httpdocs/includes/Html.php: HTML attribute tooltip-params can not contain a list of values
Backtrace:
#0 /var/www/vhosts/coldplay.wiki/httpdocs/includes/Html.php(296): Html::expandAttributes(array)
#1 /var/www/vhosts/coldplay.wiki/httpdocs/includes/Html.php(211): Html::openElement(string, array)
#2 /var/www/vhosts/coldplay.wiki/httpdocs/skins/Timeless/TimelessTemplate.php(281): Html::rawElement(string, array, string)
#3 /var/www/vhosts/coldplay.wiki/httpdocs/includes/skins/BaseTemplate.php(453): TimelessTemplate->makeLink(string, array, array)
#4 /var/www/vhosts/coldplay.wiki/httpdocs/skins/Timeless/TimelessTemplate.php(226): BaseTemplate->makeListItem(string, array)
#5 /var/www/vhosts/coldplay.wiki/httpdocs/skins/Timeless/TimelessTemplate.php(122): TimelessTemplate->assemblePortlet(array)
#6 /var/www/vhosts/coldplay.wiki/httpdocs/includes/skins/SkinTemplate.php(248): TimelessTemplate->execute()
#7 /var/www/vhosts/coldplay.wiki/httpdocs/includes/OutputPage.php(2324): SkinTemplate->outputPage()
#8 /var/www/vhosts/coldplay.wiki/httpdocs/includes/exception/MWException.php(204): OutputPage->output()
#9 /var/www/vhosts/coldplay.wiki/httpdocs/includes/exception/MWException.php(244): MWException->reportHTML()
#10 /var/www/vhosts/coldplay.wiki/httpdocs/includes/exception/MWExceptionHandler.php(69): MWException->report()
#11 /var/www/vhosts/coldplay.wiki/httpdocs/includes/exception/MWExceptionHandler.php(180): MWExceptionHandler::report(MWException)
#12 /var/www/vhosts/coldplay.wiki/httpdocs/includes/MediaWiki.php(528): MWExceptionHandler::handleException(MWException)
#13 /var/www/vhosts/coldplay.wiki/httpdocs/index.php(43): MediaWiki->run()
#14 {main}`
